version : '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5174"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:5000"