version : '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  server:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4050:4050"